import './globals.css'
import type { Metadata } from 'next'

// ! ---- This is fonts ---- !
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })
// ! --- End of fonts ---- !

// --- Layout
import Nav from "@/components/Layout/Nav"
import Footer from "@/components/Layout/Footer"

// --- Global Context
import {GlobalContextProvider} from "@/context/Global"

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body  /* className={inter.className} */ className='bg-color' >
      <GlobalContextProvider>

        <Nav />
        {children}
        <Footer />
        </GlobalContextProvider>

      </body>
    </html>
  )
}
