import type { Metadata } from 'next'
import './globals.css'

// components
import Layout from "@/components/Layout"

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Layout/>
    </html>
  )
}
